### ISSUE TITLE
Wrapper: options object is an option parameter, but an error is thrown if it is omitted.

### ISSUE THREAD

**Issue by StevenJNPearce** [aragon/aragon.js#130]
If `options.apm` is omitted, or the options object is omitted entirely an error is thrown. Additionally, `options.apm` is undocumented: only `options.provider` and `options.ensRegistryAddress` are listed in the documentation.

See line 75 in aragon-wrapper/index.js
`cov_2bk7erqz0c.s[64]++;this.apm=(0,_apm2.default)(this.web3,(0,_assign2.default)(options.apm,{ensRegistryAddress:options.ensRegistryAddress,provider:options.provi
der}));// Set up the kernel proxy
TypeError: Cannot convert undefined or null to object`

**Comment by Quazia** [comment]
Thanks for the report! This should be enough I'll let you know if we need any more.

**Comment by Quazia** [comment]
Resolved this by just setting the options to an empty array if they arn't defined and seems to be working fine. Looking at it more it's a little confusing what the apm option is actually being used for since it seems like it's main purpose is to supply an ipfs provider? Maybe it would make more sense to change the option name to reflect this?

**Comment by sohkai** [comment]
@Quazia Yes... this whole apm initialization bit should be cleaned up.

`options.apm` is meant for any `apm.js`-related set up, e.g. custom apm providers (aside from http and ipfs), alternative ENS registries to look up, or an ipfs-api config.

Given how aragon.js is using apm.js, I think it'd make sense to flatten these options and do away with a custom `apm` config option.
