### ISSUE TITLE
Implement minGas for intent arguments

### ISSUE THREAD

**Issue by izqui** [aragon/aragon.js#150]
> @sohkai: add something like minGas to specify a lower bound on gas. I think the cases where gas estimation get stuck is when it estimates a really low amount of gas so this could avoid that while still allowing for higher cost operations like forwarding.

With https://github.com/aragon/aragon.js/pull/131 we started allowing apps to specify some transaction options for execution such as the gas limit. As it is pointed out above, it would be great to add a special `minGas` argument (or maybe treat the `gas` argument as `minGas`?) so apps can specify a lower bound for the gas limit of an intent.

**Comment by PascalPrecht** [comment]
Just to clarify: `minGas` is supposed to be used as gas limit in transactions, in case a calculated gas limit is below `minGas`, is that correct?

**Comment by izqui** [comment]
The idea is that if `minGas` is provided as an intent parameter, if the gas estimation for the transaction is lower than `minGas` then the gas would be set to `minGas`, but if the gas estimation for the intent were higher we would set the gas to the estimation.

**Comment by PascalPrecht** [comment]
Discussed this offline with @izqui and we decided to not introduce a new property `minGas` but rather have `gas` act as min gas, in case it's lower than estimated gas.

So the rule is to use gas only when it's higher than estimated gas.

**Comment by PascalPrecht** [comment]
Discussed this offline with @izqui and we decided to not introduce a new `minGas` property but rather treat `gas` as `minGas`

**Comment by PascalPrecht** [comment]
Further, @izqui and I discussed to perform a similar gas estimation as metamask does, meaning that it adds a little buffer to the estimated gas while staying within the block gas limit.

Here's the crucial bit: https://github.com/MetaMask/metamask-extension/blob/955ec2dca620f25beb2c7cd24c059f6ac22fdebe/app/scripts/controllers/transactions/tx-gas-utils.js#L110-L122

In order to do the same thing, it looks like we need to request the latest block gas limit. Metamask is using [ethjs-query](https://github.com/ethjs/ethjs-query) for that. I guess we can take advantage of `web3.eth.getBlock('latest')` and make our calculations based on that.

I hope this makes sense. If there's no concerns here I'd just go ahead and try to implement this for feedback.

**Comment by izqui** [comment]
Sounds good to me @PascalPrecht. I read the code and the only thing that worries me is the hard cap at 90% the gas limit of the previous block, we could make that a little bit higher.
