### ISSUE TITLE
Add utilities to describe transactions

### ISSUE THREAD

**Issue by onbjerg** [aragon/aragon.js#16]
The function should be able to describe "vanilla" transactions and transactions with EVM callscripts, which might include EVM callscripts further down (yes, deeply nested callscripts are a thing).

**Steps**

- Find a way to identify transactions with callscripts to separate the two types
- For callscripts, split the callscript into individual "vanilla" transactions
- Describe each "vanilla" transaction individually

**Types**

```js
type TransactionDescription = {
  description: string
}

type DescribedEthereumTransaction = EthereumTransaction & TransactionDescription
```

**Comment by izqui** [comment]
For a first iteration of describing txs, we should evaluate as little as possible to reduce the possibility of it becoming vulnerable to [executing malicious code](https://hackernoon.com/how-one-hacker-stole-thousands-of-dollars-worth-of-cryptocurrency-with-a-classic-code-injection-a3aba5d2bff0). Also the context of the application instance is important to understand the transaction correctly.

In the case of `TokenManager.assign(address _receiver, uint256 _amount)` its [notice](https://github.com/aragon/aragon-core/blob/dev/contracts/apps/token-manager/TokenManager.sol#L117) is:

```Assign `_amount` of tokens for `_receiver` from Token Manager's holdings```

The problem is that both `_amount` and `_receiver` values aren't descriptive enough, the amount is expressed as the full number (without taking decimals into account) and the receiver is just a hexadecimal address. So it is needed to perform some transformations in order to make transaction descriptions valuable.

Proposed transformations for initial version:
- `identity(addr)`: Instead of just going with `_receiver`, `identity(_receiver)` displays a human readable name if known. Could be an entity name or an application with its context.
- `token(addr)`: Displays token name or symbol of token at address
- `formatTokenAmount(addr, amount)`: Displays amount taking into account token decimals. In the particular case of TokenManager, the `addr` of the token is not a parameter but a state variable, so it could be something like ```Assign `formatTokenAmount(app.token,_amount)` ...```
- `date(timestamp)`: Displays timestamp as a date: `August 4th, 2018`
- `interval(time)`: Displays time unit: `1 day and 6 hours` or `3 years`

We need to figure out how to describe more complex transactions like the one needed to [start a token sale](https://github.com/aragon/aragon-core/blob/dev/contracts/apps/fundraising/Fundraising.sol#L69)

**Comment by onbjerg** [comment]
>For a first iteration of describing txs, we should evaluate as little as possible to reduce the possibility of it becoming vulnerable to executing malicious code. Also the context of the application instance is important to understand the transaction correctly.

Yes, we should definitely have a very primitive way of describing transactions until "natspec lite" is done. One way we can ensure that no malicious code is run during rendering (i.e. not parsing, which is where natspec is insecure), we should make sure to never render anything with the `dangerouslySetInnerHTML` prop in React.

**Comment by onbjerg** [comment]
Fixed in rewrite branch
