### ISSUE TITLE
Apps: add ability for apps to know if they are in the inital loading phase

### ISSUE THREAD

**Issue by bpierre** [aragon/aragon.js#206]
Could be related to #86 if we want to have the same or a similar API to get these two pieces of information.

**Comment by sohkai** [comment]
Something we could also do is detect if we're syncing a _large_ amount of blocks (e.g. >100k) and then successively call `eth_getlogs` with `to` and `from` block numbres so that we don't have to wait for the entire operation to finish at once before we process any results.

As of today, loading the `governance.aragonproject.eth` org's voting app requires >5min to sync ~1million blocks, with the `eth_getlogs` sending 20kb of data all at once at the end. We could instead split this operation into 100k block chunks to start loading data faster for the user.

**Comment by sohkai** [comment]
Closing since #297 implements this functionality, and created a new issue for the incremental sync (#331).
