### ISSUE TITLE
Return promises instead of observables

### ISSUE THREAD

**Issue by 0x6431346e** [aragon/aragon.js#226]
@0x6431346e commented on [Fri Dec 14 2018](https://github.com/aragon/aragon-cli/issues/300)

See https://github.com/aragon/aragon-app-dx/issues/2

Would be nice to add an option when initializing the app and then have promises returned.
```
const app = new AragonApp({ withPromises: true })

app.increment(1).then(
  (txHash) => console.log(`Success! Incremented in tx ${txHash}`),
  (err) => console.log(`Could not increment: ${err}`)
)
```
instead of
```
const app = new AragonApp()

app.increment(1).subscribe(
  (txHash) => console.log(`Success! Incremented in tx ${txHash}`),
  (err) => console.log(`Could not increment: ${err}`)
)
```

**Comment by sohkai** [comment]
I was even thinking this could be done immediately, as part of the existing `@aragon/client` version. We already have a lot of observables (from `sendAndObserveResponse()`) that emit a single value and end and could be turned into promises.

**Comment by galactusss** [comment]
Daniel I like d039b1e 
About 184c8a8 I don't understand as much aragon.js and observables to know if could be possible to make it backwards compatible. But seems reasonable to have a workaround if the user want to use observables

**Comment by sohkai** [comment]
> What do you mean by "as part of the existing client version" ?
> Something like this: d039b1e ?
> What about methods like state/network/accounts that emit over time? It wouldn't be possible to get updates anymore.

Ah, I thought we were on a beta version of the client already, but we aren't.

I was thinking that the changes to make any single-value calls (i.e. those that use `sendAndObserveResponse()` rather than the multi-value `sendAndObserveResponses()`) return promises is really trivial and would already help a lot of people who may never want to use the other APIs that return observables.

We could release it as a 2.0.0 as an intermediary step towards the full simplified API in https://github.com/aragon/aragon-app-dx/issues/2. Technically, if you wanted to still use RxJS operators on the promises, you could, as most operators that expect an observable input can also receive a promise, so there's very little lost from this transition.

> which I tried implementing in 184c8a8, but this means we can't keep the RxJS API, making this backwards incompatible.

I'd say the goal of https://github.com/aragon/aragon-app-dx/issues/2 is basically to hide the RxJS API, as it's not well understood by a lot of developers ;).

**Comment by 0x6431346e** [comment]
> We could release it as a 2.0.0 as an intermediary step towards the full simplified API in [aragon/aragon-app-dx#2](https://github.com/aragon/aragon-app-dx/issues/2). Technically, if you wanted to still use RxJS operators on the promises, you could, as most operators that expect an observable input can also receive a promise, so there's very little lost from this transition.

Oh, I don't think that will add a lot of value though, having 2 major releases, especially since we can move quickly with https://github.com/aragon/aragon.js/pull/230 and release it in the next couple of days.

**Comment by sohkai** [comment]
Closing for #264.
