### ISSUE TITLE
Expose IPFS gateway to apps

### ISSUE THREAD

**Issue by luisivan** [aragon/aragon.js#256]
A use case like https://github.com/P2PModels/wiki would benefit from having an IPFS instance. Not only to read, but also to write. That, of course, is only possible if we have an IPFS client inside the Aragon client.

In that case, an app would have its own sandboxed storage, and could read and write using an aragonAPI intermediate API.

**Comment by sohkai** [comment]
Would they want their own IPFS instance or piggy back off of the gateway that the Aragon client itself is connected to?

When we do bundle an IPFS node with an Aragon client, like on Aragon Desktop, we could provide that API endpoint to apps, but at the end of the day this would just be a URI you connect `ipfs-api` to and shouldn't require any sandboxing or other APIs from aragon.js.

You may also be able to run an entire IPFS node in a webworker, but that sounds really sketchy.

**Comment by luisivan** [comment]
I'm guessing piggyback to the instance the client is connected too. This would only be useful to push content to IPFS on Aragon Desktop, since the default remote is read-only. I think pushing to IPFS is something that will be required more and more (e.g. metadata, identity) so I think we need to find if it's a deal breaker for Aragon on browsers. Maybe the only way to solve it is to literally run IPFS on the browser.

**Comment by sohkai** [comment]
> I think pushing to IPFS is something that will be required more and more

The problem with this is what happens to that data if you don't pin it. Even if you run IPFS in the browser, you're still going to have availability issues. You only solve this problem if you can ensure there's a node you can connect to that will pin your data (e.g. Aragon Desktop), and that sounds like an app-level problem.

An even bigger problem is what happens if _someone_ else wants this information you push (e.g. your identity). Even if _you_ pin this information on a local node, as soon as you go offline it becomes more or less unavailable for others.

**Comment by luisivan** [comment]
This is true. Probably not a good idea in the short term until we have something like Filecoin, and then the DAO can literally pay for storage and we can include the API then.
