### ISSUE TITLE
Errors inside app.store reducers are not thrown

### ISSUE THREAD

**Issue by sembrestels** [aragon/aragon.js#262]
Errors occurried inside store reducers are not shown in console. The following code fails silently, for example:

```js
app.store(
  (state, event) => {
    throw new Error('hi')
    return state
  }
)
```

On the other hand, if we put an Error in the reducer used in the [test](https://github.com/aragon/aragon.js/blob/master/packages/aragon-api/src/index.test.js#L235), it is thrown as expected. I don't know why.

Anyone have any idea why errors are dismissed inside app.store?

**Comment by sohkai** [comment]
It may be that the console isn't showing the logs from the webworker, or the error isn't making it to the top level (to trigger the webworker's `onerror`) because it's in a observable's handler.

In any case, perhaps the easiest fix for this would be to insert a try / catch when we execute the given store reducer: https://github.com/aragon/aragon.js/blob/master/packages/aragon-api/src/index.js#L197.
