### ISSUE TITLE
`api.cache` not persisting values in state

### ISSUE THREAD

**Issue by Schwartz10** [aragon/aragon.js#357]
I'm running version `@aragon/api@2.0.0-beta.5` and tested the following code snippets:
```js
api.cache('key', 'value').subscribe(() => {
  api.state().subscribe(console.log)
  // key => value not returned
})
```

```js
api.cache('key', 'value').subscribe(() => {
  api.getCache('key').subscribe(console.log)
  // null returned
})
```

Am i doing something wrong here? 

I see some other errors in my application console, and I don't _think_ they seem related - other API methods are working (like sending intents).

**Comment by sohkai** [comment]
`state()` definitely won't return the value, since `state()` is only looking for the `state` key, but `getCache()` should work.

However, `getCache()` currently uses a [`Cache.observe()`](https://github.com/aragon/aragon.js/blob/master/packages/aragon-wrapper/src/rpc/handlers/cache.js#L6) in the handler and we should change this to `Cache.get()`.

In any case, the second example should've worked, and unless there's something funny with the IndexedDB cache on your browser.

**Comment by Schwartz10** [comment]
This was my mistake - overlooked some things on my end. It's working properly. Sorry for any confusion!
