### ISSUE TITLE
Q: app.store docs need updating?

### ISSUE THREAD

**Issue by Schwartz10** [aragon/aragon.js#358]
I'm upgrading to the latest `@aragon/api`, and realizing I need to change the second params of the `api.store` method, which don't seem to be updated in the docs yet. 

The docs say to pass an array of home-made events into the store as the second argument: https://github.com/aragon/aragon.js/blob/master/docs/API.md#store

The latest code implies [otherwise](https://github.com/aragon/aragon.js/blame/c08bad3eb5029d71171a0d23b1f29499cd3cf28c/packages/aragon-api/src/index.js#L403).

Another question is how to handle the array of `externals` - according to the code, I've made this change:

```js
{
  externals: [
    {
      contract: addressBook
    },
    {
      contract: vault
    }
  ]
}
```

Question is - how can we provide a `from` argument to the external contract events like we were doing before? We'd love to only scrape events from the initialization block of these contracts. Is that handled by the API now?

**Comment by Schwartz10** [comment]
Also, we relied on some home-made event code where we passed a multi-emission observable into the `external` array (those observable weren't from contract `event.calls`). For example, when certain values were set in the aragon/cache, we emit an event that the background script handles like any other event. Since the `init` method seems to just initialize the store, and the `external` events array is purely for contracts, how can we imitate this same behavior?

**Comment by sohkai** [comment]
Yes, they do need updating and it's one of many things on my list of things to do.

> Question is - how can we provide a from argument to the external contract events like we were doing before? We'd love to only scrape events from the initialization block of these contracts. Is that handled by the API now?

[You can optionally provide an `initializationBlock` alongside the `contract`](https://github.com/aragon/aragon.js/blob/master/packages/aragon-api/src/index.js#L399).

> One idea is to have an api method called dispatch or emit which is just responsible for dispatching home-made actions to the store, redux-style

Would something like #119 work, or are you triggering events inside the background script directly (in that case, could it be handled in the same reducer?)?

I pushed to remove the last `events` argument from `store()` in APIv2 as my hope is to include everything a user needs into the store itself, rather than having to figure out how to implement this functionality themselves (e.g. accounts switching, new apps, etc.).

**Comment by Schwartz10** [comment]
Awesome, thanks for the additional information and all makes sense. 

#119 is exactly what we need - any idea where that feature sits in terms of priorities?
