### ISSUE TITLE
Bundle with regenerator-runtime

### ISSUE THREAD

**Issue by onbjerg** [aragon/aragon.js#47]

**Comment by sohkai** [comment]
Or make it a peer dependency? Usually the consumer provides the polyfills.

**Comment by onbjerg** [comment]
I agree it might be better to add it as a peer dependency. What do you think @bpierre?

**Comment by bpierre** [comment]
I agree, let’s add it as a peer dependency for now.

Another approach would be to disable regenerator in the .babelrc, since [ES6 generators](https://caniuse.com/#feat=es6-generators) and [await / async](https://caniuse.com/#feat=async-functions) are well supported now.

**Comment by onbjerg** [comment]
@bpierre I feel like the second approach is better, since we should really only support modern browsers for security reasons as well. Bringing in @izqui and @luisivan - what do you think about only supporting the browsers listed in Pierre's link?

**Comment by onbjerg** [comment]
@bpierre Using the same `babel-preset-env` configuration as Aragon UI still transpiles async/await, and I suppose it is for good reason. Maybe we should indeed just bundle the runtime?

**Comment by bpierre** [comment]
> Maybe we should indeed just bundle the runtime?

Having thought more about it, I agree that we should bundle the runtime transform: it doesn’t pollute globals and it is meant to be used from libraries, not apps. We only have to be careful about the instance methods we use ([see the note here](https://babeljs.io/docs/plugins/transform-runtime/)).

> Using the same babel-preset-env configuration as Aragon UI still transpiles async/await

I think we should transform it in Aragon UI (if we use async / await one day), because it needs to support a larger variety of browsers than aragon, aragon-apps and aragon.js (e.g. for the website).

Maybe we could agree on using preset-env browser queries similar to these:

- aragon-ui: `>1%`
- aragon / aragon-apps / aragon.js: `>2%, not ie > 0, not op_mini all`.

I excluded IE and Opera Mini because their JS support is limited, and there is no reason to run Aragon there.

**Comment by onbjerg** [comment]
@bpierre I think I recently copied the env preset config from Aragon UI. In general, we should probably support as modern browsers as possible, and be very strict about what browsers we support, for security reasons. In this space, I think we're allowed to do so.

This is the current `.babelrc`:

```json
{
  "targets": {
    "browsers": [
       "> 1%",
       "last 3 versions",
       "ie >= 9",
       "ios >= 8",
       "android >= 4.2"
    ]
  },
  "useBuiltIns": false
}
```

**Comment by bpierre** [comment]
> In general, we should probably support as modern browsers as possible

I strongly agree with that 🙌

> and be very strict about what browsers we support, for security reasons

I don’t think it is the place to do that. For example, we could decide to not support a browser for security reasons, but this browser could support all the JS features we ship in our code, and will therefore be “supported” (in the sense that the app doesn’t break).

The babel-preset-env query is a bit confusing because it can be understood as “we only support these browsers”, while what it really means is “we guarantee that our code will run on these browsers, or any other supporting the JS features we use”.

About forbidding access to some agents, I think we should try to never exclude any browser explicitly. People should be free to use the browser they want, even if we never heard about its user agent, as long as web standards are supported. Now, if we hear about a serious security issue affecting a specific user agent, then we could exclude it explicitly and temporarily to protect our users, but it should be done by detecting the agent, and not by trying to use a specific JS feature that is not supported on this specific browser in order to break the app.

Here is the current browsers for the three queries in this discussion:

```
> 1%

and_chr 64
and_uc 11.8
chrome 63
edge 16
firefox 57
ie 11
ios_saf 11.0-11.2
ios_saf 10.3
op_mini all
safari 11
samsung 6.2
samsung 4
```

```
> 2%, not ie > 0, not op_mini all

and_chr 64
and_uc 11.8
chrome 63
firefox 57
ios_saf 11.0-11.2
```

```
> 1%, last 3 versions, ie >= 9, ios >= 8, android >= 4.2

and_chr 64
and_ff 57
and_qq 1.2
and_uc 11.8
android 62
android 4.4.3-4.4.4
android 4.4
android 4.2-4.3
baidu 7.12
bb 10
bb 7
chrome 64
chrome 63
chrome 62
edge 16
edge 15
edge 14
firefox 58
firefox 57
firefox 56
ie 11
ie 10
ie 9
ie_mob 11
ie_mob 10
ios_saf 11.0-11.2
ios_saf 10.3
ios_saf 10.0-10.2
ios_saf 9.3
ios_saf 9.0-9.2
ios_saf 8.1-8.4
ios_saf 8
op_mini all
op_mob 37
op_mob 12.1
op_mob 12
opera 50
opera 49
opera 48
safari 11
safari 10.1
safari 10
samsung 6.2
samsung 5
samsung 4
```

For Aragon UI, I think the `>1%` is conservative enough: if our codebase is compatible with Opera Mini and IE 11, any other agent should be fine.

For aragon / aragon-apps / aragon.js, I think even the  `>1%` query is too conservative. Having IE 11 / Opera Mini as our lowest common denominator means that our users will run unnecessary polyfills instead of native JS features, in order to support a use case that doesn’t exist, because these browsers will never support web3. That’s why I excluded them explicitly in the second query.

What do you think?

**Comment by sohkai** [comment]
> Having IE 11 / Opera Mini as our lowest common denominator

100% agree on avoiding these for anything relying on web3.

Could we do `> 2%, not ie > 0, not op_mini all` but with support for Edge (not sure if `not ie` also removes Edge)?

**Comment by bpierre** [comment]
> not sure if `not ie` also removes Edge

It doesn’t, but the `> 2%` does. I agree we could include it explicitly for aragon / aragon-apps / aragon.js, I don’t think a web3 environment exist for it, but it is a major browser and it might become true one day. Also it won’t change much if anything in our shipped code, because its JS support is excellent.

So the new proposed query for aragon, aragon-apps and aragon.js would be:

```
>2%, last 1 edge versions, not ie > 0, not op_mini all

and_chr 64
and_uc 11.8
chrome 63
edge 16
firefox 57
ios_saf 11.0-11.2
```
